modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Viral Public License"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="miladycapes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Miladycraft Capes" #mandatory
#logoFile="examplemod.png" #optional
credits="forked from Kay9's ItemCapes mod for 1.16.5" #optional
# A text field displayed in the mod UI
authors="virtualonno" #optional
description='''
Custom capes implemented as Curio items.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.miladycapes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.miladycapes]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.miladycapes]]
modId="curios"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

